CREATE TABLE auth.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100),
    last_name  VARCHAR(100),
    phone_number VARCHAR(30),
    address VARCHAR(255),
    city VARCHAR(100),

    user_id BIGINT UNIQUE,

    CONSTRAINT fk_customers_user
        FOREIGN KEY (user_id)
        REFERENCES auth.users(id)
        ON DELETE CASCADE
);
